CREATE TABLE IF NOT EXISTS tutorials (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  author_id BIGINT NOT NULL,
  title VARCHAR(120) NOT NULL,
  category VARCHAR(24) NOT NULL,
  difficulty VARCHAR(24) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  materials JSON NOT NULL,
  steps JSON NOT NULL,
  views INT NOT NULL DEFAULT 0,
  favorites INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(40) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL,
  specs JSON NOT NULL,
  images JSON NOT NULL,
  sales INT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  items JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
